config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

  def update
    # @flat.update
    # redirect_to flat_path(@flat)
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :img_source)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :img_source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", flat: @flat %>

<br>
<div>
  <%= link_to "Show this Flat", @flat %> |
  <%= link_to "Back to Flats", flats_path %>
</div>

app/views/flats/index.html.erb
<div class="container d-flex justify-content-between align-items-center mt-2 m">
  <h1>Flats</h1>
  <div><%= link_to "New Flat", new_flat_path %></div>
</div>
  <div style="height: 50px;"></div>

<div class="container d-flex flex-direction-row mt-5">
  <% @flats.each do |flat| %>
    <div class="card flat mt-3">
      <img src=<%= flat.img_source %> alt="Flat">
      <h2><%= flat.name %></h2>
      <p><%= link_to "Show this Flat", flat %></p>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to Flats", flats_path %>
</div>

app/views/flats/show.html.erb
<div class="container mt-5 m-auto img">
  <div><h1><%= @flat.name %></h1></div>
  <div><img class="img" src=<%= @flat.img_source %>></div>
  <div><%= @flat.address %></div>
  <div><%= @flat.description %></div>
  <div><%= @flat.price_per_night %></div>
  <div><%= @flat.number_of_guests %></div>
</div>

<div class="img m-auto">
  <%= link_to "Edit this Flat", edit_flat_path(@flat) %> |
  <%= link_to "Back to Flats", flats_path %>
  <%= button_to "Destroy this Flat", @flat, method: :delete %>
</div>

<%# <div><%= link_to "Leave a review", new_flat_review_path(@flat)</div> %>

<%# <div>
  <% @flat.reviews.each do |review| %>
    <%# <h3 class="p-3 mb-2">
      <%= review.content %>
      <%# <%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <%# </h3>
  <% end %>
<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>